# site settings
title: M치rques
subtitle: by M치rques
email: rippleytrigger@gmail.com
description: A responsive site designed by M치rques <br /> and released under the Creative Commons.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: M치rques
street_address: Rambla Onze de Septembre, 62-64
city: Barcelona
state: Ca
zip_code: 08030
country: Spain
phone: (+34) 692-661337

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/andrewbanchich
  GitLab:
  Google-Plus: https://plus.google.com/u/0/+AndrewBanchich
  Instagram:
  LinkedIn: https://www.linkedin.com/in/andrew-banchich-a4ba1195
  Twitter: https://twitter.com/andrewbanchich
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
